{% set name = "flake8-quotes" %}
{% set version = "3.3.1" %}
{% set sha256 = "633adca6fb8a08131536af0d750b44d6985b9aba46f498871e21588c3e6f525a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 111.diff

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - python >=3.5
    - flake8

test:
  imports:
    - flake8_quotes
  commands:
    - flake8 --version

about:
  home: https://github.com/zheller/flake8-quotes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Flake8 lint for quotes.
  description: |
    Now you don't need to worry about people constantly complaining that you are
    using double-quotes and not single-quotes.
  doc_url: https://pypi.python.org/pypi/flake8-quotes
  dev_url: https://github.com/zheller/flake8-quotes

extra:
  recipe-maintainers:
    - flamingbear
    - michaeljb
    - dopplershift
    - matthiasdiener
