travis:
  secure:
    BINSTAR_TOKEN: cD1wJqiiLY5C/np3kBHl0kNyCd1qcXEHBvqMDknYqdCB3NSCj1Q909dYILNbZMnbL3/WMn5xJainJg+jmd9D6Q6bVhD9CbDhQieTelYLDkHsA7L5HUdJKOK4xXNAyjAiwgLZAUwUHXpagQ3ceoBCjnknxIMgbYDTxwaHGsyUMoa2ObB3YK2G34eAjL2rhlElSGUFyJnpxA2VJkNQlBhCLBF1NUXs+pz+xmgCSIAXXaeDQ3uiYIKgX5wrOd7tw1zPy1ZERAtg759ZEIZ97wv40s/7FQzka1dAjgYx2WMyGZOg+AUZQooYqCnM9PWj5yur4jblt/QzEZjf4fnmX9Qsg8imkU7vjJNyUQUZecMx8vxHQGLbDKtUM2TyAOK1yMUhDZY4+F16ChHpysaXklsTMgd+NDDOGlUG6/hTmoK4GiBFzyTQCpJnkKPV9eRNnfZ3+fAOOsM5FBT8yOpK7MOrAEAqjYFHpyla6jxZdcb1GRpm5Bjrbphdw5SDrISfrl+4kXQWQx5kPSly1JY/5ylLZOctaYmU+EM1BLlAZE/8XY88nUOV8PY+xPMr3FtrCW4XGt3ppnppfghbIWiqpMdXmPawaA4McBmG8M1aJsL/EG6uH05Bfl/PtYWCskv6ns7gOKke//fl5MY6NdN8cGZzRsY4ik1oJvmvYZrV0tro2a4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
