travis:
  secure:
    BINSTAR_TOKEN: Aj/wGnZ32WivahdEW6NG6J5WJZFdOlWXAWOfwoBd6hnju+djj7KJ8uihEdslMmXoGTHosnBKjnzzB/+dS2q32m8EoqkQPwUfT22HHafDdyflppQqnpp3DQehUi4kajTovl3YgLTPPp/wbWtOMKBKH3okvip3lIXOHpKwFgjErqrZCgKBHsvFEMk7j6QMXHjurMuqSxuE4KLakmXs4Y5URJR3nbLU8dQlUdMAKQxpft6/r4M2OKIyjrd0VSKPemrr6Xb4O2MopYC/Mh1Oq/pgPQY3Z71O0i4x3CwuxOQErKzcJh50FgyeoDNmSz4mWa33TyBq+FTgQMt1H9ai4HJDcFuWw0ntWWu/GqMh9zDGia030u8Gt7fyA01akAcH+pCKggWPZjQyfKmnIpecBMidDCzX+OecCVGt5VBNevWb8d1oCxqcYZW6wfTcNJk4hdKBaqu40y5KKdliBfG7q1HC8mddGjcdXtGk1L4/vtvuDPV+Al0qRvaFsl18054j6YTkc6dVRxbvJDMoPPDP/e1qX+c199sDadkh2d8PoP7ynXOIQBW2++1ptPZJYIo+OGv3wtX6xeyh6rR9L7MaMJpxcUVMy4IcDyccSZjB8Nc6dfehvvt3l9WuJfDoW7eFCBvcison3P4iHNZIe0Yhl8DheosQB5oK4RolmaKrdeIU6e4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
