travis:
  secure:
    BINSTAR_TOKEN: Wl/50K0XBfbfQDiSLYtwvzHgzPVn++xf+ODy2A8QLbYMDIZhS6HIxFR7f5DJCPl6RWt+RK3M4cWiOnl4zzpllSrAXdg58Gh0ssQhF1gzxdCKp7XhBCNXKJohLXPS4tM5sZNFBz+pMrJ2WNezASf9VtX7p3MprL4NxWx+paDGhw9kFDDBQY+gXdXD+kFaIDp87Yq4TKS2t6cu7inYKw+WsPLT0U9opSowVp4dHu8bHfNbUw9mzujytnvFHjd+9h/pK8GiGIs2reAxoj6yIQnBJBb7hy3x2s3GNc1aVZWh828As3GH76gcUATXnflrxCaFITZ0mzjjrOdDQoEGDuOVkAdtckjNYD7LTcCSdk+LvBMcdT5XVkN8oZLg2G+UV+J45URVXxjDnCqF70gyGcwg6mTml35UdCOUoqmpZl1X9sjZre01Fkf6vO/BV5z2ba6Pd+OnYIuE0VPYKZrqOpeHBj16M5IaaseiP9uYnrWdGG+xgK3KJ7WnQUb/83bvVtsvv/WNfuUGjlxqGISYZI2Lifxd1fmPEnRoDqZQ7kEPoSFNtepOL7NsC6QK+xcgAlPpmAuqIi6Ck/Mh4SQxdKybQdX43UOV6VLOpLy9oIctE5rJY9TpexThjBVt69pv4UO11ItoysMTD13pki+DToZAd7eUEtBFWni89INhbJAvWXk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
